### ISSUE TITLE
Keep some record the network.

### ISSUE THREAD

**Issue by urbanslug** [goodbotai/karma#24]
### Environment
All

### Expected behavior
We should be able to trace network growth and flow

### Actual behavior
All nodes in the network just pop up independently. We don't store who added who to the network.

### Steps to reproduce the behavior
Share the bot, when the recipient starts using the bot there won't be a record who shared it with you.

---

### Implementation plan

- [x] Add a referrer field to our rapidpro contacts
- [x] get the rapidpro user id for the current user before sharing
- [x] insert this id to the ref section of the share url
- [x] when a bot url is clicked save the userid of the referring user as a referrer in the user's contact

Also explained here https://github.com/goodbotai/karma/issues/30#issuecomment-329793608

**Comment by pld** [comment]
From #30 

> We shall add a ref to the bot link the ref value shall be the referrer's Rapidpro contact ID.
> Basically we shall have the URL here https://github.com/goodbotai/karma/blob/master/karma.js#L389 be http://m.me/1504460956262236?ref=
> When a user clicks this referral link we will store the ID of the user who referred them in their rapidpro contact.
