### ISSUE TITLE
Clarify socialConcernChangeScale

### ISSUE THREAD

**Issue by hipstermojo** [goodbotai/karma#82]
### Environment
All

### Expected behaviour
Should have an explanation for 1 to 10 or have two choices namely, better and worse.

### Actual behaviour
![screen shot 2017-11-16 at 15 14 01](https://user-images.githubusercontent.com/25569504/32890817-675b283e-cae1-11e7-8c4f-b0862727784a.png)

### Steps to reproduce the behaviour
Have a conversation with the bot and say yes to having spoken to someone about it recently.

---

### Implementation plan

- [ ] Get clarification on https://github.com/goodbotai/karma/blob/master/translations/en.json#L18
- [ ] Request for In translation
- [ ] Request for Pt translation

**Comment by urbanslug** [comment]
Looking at the doc with the spec there's a scale "Worse 1-10 Better".
